version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_ROOT_PASSWORD: secret
      POSTGRES_USER: buss
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    network_mode: host
